### ISSUE TITLE
Add "About Plausible" entry

### ISSUE THREAD

**Issue by TheEvilSkeleton** [cassidyjames/plausible#25]
There is no easy way currently to check what version Plausible is running.

I'd like to suggest doing it similarly to GNOME, where you press a triple dot button, press on `About Plausible`, and it shows its version, credits, etc.

https://user-images.githubusercontent.com/50847364/108929879-d762d700-7612-11eb-86da-b904334b51e7.mp4

**Comment by cassidyjames** [comment]
Since the app is primarily designed for elementary OS, I'll be following elementary design conventions: https://blog.elementary.io/peace-out-about-dialogs/

**Comment by cassidyjames** [comment]
Since the app follows GNOME conventions now, I'll add this. :)
