### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by TheEvilSkeleton** [cassidyjames/plausible#30]
We should make a new release with the latest commit. At least we'll be using the latest version of the GNOME runtime and elementary base app.

**Comment by cassidyjames** [comment]
@TheEvilSkeleton hm, I haven't been testing from `master` as much, but I can definitely see value in getting the deps bumped. Honestly I'd like to work on a larger rethinking of the UI soon, but I suppose that can wait.

**Comment by cassidyjames** [comment]
@TheEvilSkeleton things broke when I tried to bump the deps without code changes (even though I didn't think _that_ much changed!), so instead, I'm working on a first-pass port to GTK4 and the GNOME 43 runtime that's coming along nicely in #32.
