### ISSUE TITLE
Add build instructions to README

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/plausible#4]
It's just a meson app like my other GTK/Vala apps.

**Comment by TheEvilSkeleton** [comment]
I am offering help. You can tell me all the commands that are available and a brief description of what they do, and I will write the README.

If you want to write the README yourself, then I'm okay with it.

In case you want to see some of the work I've done, you can take a look at some projects I have contributed:

- https://github.com/tsujan/Kvantum/commits/master/Kvantum/INSTALL.md?author=TheEvilSkeleton
- https://github.com/GloriousEggroll/proton-ge-custom/commits/proton-ge-5-MF/README.md?author=TheEvilSkeleton
