### ISSUE TITLE
After login, "Error 500" appears

### ISSUE THREAD

**Issue by ghost** [cassidyjames/plausible#41]
![image](https://user-images.githubusercontent.com/51213244/210156922-9bd2a96e-35c5-4b4e-b460-600b70168f5d.png)

In version v3.0.0 of Tally, I went to log into Tally and ran into error 500.
I first thought that there may be an issue with my selfhosted instance of Plausible, and that wouldn't surprise me, but trying again in a web browser did work for me.

The error 500 only happens to me in the Tally app.

**Comment by ghost** [comment]
Happens when clicking the login button, doesn't when just pressing enter to login. Bit weird.

**Comment by cassidyjames** [comment]
@KorbsStudio was this resolved? I wonder if it was something server side.

**Comment by cassidyjames** [comment]
@KorbsStudio was this resolved? I wonder if it was student server side.
