### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/plausible#5]
It's probably not kosher to call the app “Plausible” unless it's official. If we don't think we'll get official status, we should rename to something like “Foo for Plausible Analytics,” like most third-party Reddit apps do.

**Comment by cassidyjames** [comment]
@metmarkosaric do you have opinions about a rename? It's pretty common for third-party apps to do the whole “AppName for ServiceName” pattern, which I'd be happy to do here. E.g. "Sync for Reddit" or "Foo for Plausible".

**Comment by metmarkosaric** [comment]
I'm happy for it to stay Plausible or Plausible Analytics @cassidyjames . It's a wrap around our site so I see no reason for it to be renamed unless obviously you prefer to call it something different.

**Comment by cassidyjames** [comment]
Great! Closing, then.

**Comment by cassidyjames** [comment]
Re-opening because referring to the app itself is awkward without having its own name. E.g. something like "Plausible supports self-hosted Plausible instances at your own domain" doesn't make it clear if Plausible (the open source project or service) supports that, or if this specific app does.

I'm thinking about something simple and following in the convention for Reddit apps, like "Dashboard for Plausible" or maybe something less generic/more quirky like "Metrlytics for Plausible" and then just referring to it as "Metrlytics" internally. Idk.

**Comment by cassidyjames** [comment]
Or maybe thinking about synonyms for what Plausible does (analytics, metrics, counting, etc.), I kind of like "Tally for Plausible". There doesn't seem to be any collision on Flathub, either.

**Comment by cassidyjames** [comment]
If anyone _(summons @micahilbery)_ wants to throw an icon together in GNOME style using the Plausible colors... the name is a reference to a [physical tally counter](https://duckduckgo.com/?q=tally+counter&t=epiphany&iax=images&ia=images). :smile:
