### ISSUE TITLE
Change RDNN

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/plausible#8]
>I'd like to ask a question about the ID. Can you change the ID from [`com.github.cassidyjames.plausible`](https://github.com/cassidyjames/plausible/search?q=com.github.cassidyjames.plausible) to `com.cassidyjames.Plausible` (or without the capital P)? Since you have a domain, I think it would be better if the ID can be trimmed down; I won't mind changing a bit of the manifest.

–@TheEvilSkeleton in https://github.com/cassidyjames/plausible/issues/2#issuecomment-780900374

**Comment by TheEvilSkeleton** [comment]
I personally wouldn't mind to use `com.github.cassidyjames.plausible` instead. It's just a suggestion I think would fit better.
